name: Deploy Static Content to GitHub Pages with Let's Encrypt SSL

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSL with Let's Encrypt (via Certbot)
        run: |
          sudo apt update
          sudo apt install -y certbot

          # Replace with your own domain
          DOMAIN="www.pradeepn.in"

          # Using Certbot to obtain the certificate for your domain
          sudo certbot certonly --non-interactive --agree-tos --email contact@pradeepn.in -d $DOMAIN

          # Copy certificates to the necessary directory
          sudo cp /etc/letsencrypt/live/$DOMAIN/fullchain.pem /path/to/certificate.crt
          sudo cp /etc/letsencrypt/live/$DOMAIN/privkey.pem /path/to/private.key

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
